import { test, expect } from '../fixtures'
import type { Page } from '@playwright/test'
import type { ApiClient } from '../helpers/api'
import { env } from '../helpers/env'
import { rawPrisma } from '../../src/lib/db'
import { signPlatformAuthToken } from '../../src/lib/auth/platform-auth'

type AnyRecord = Record<string, unknown>

function recordsFrom(data: unknown): AnyRecord[] {
  if (Array.isArray(data)) return data.filter(isRecord)
  if (!isRecord(data)) return []

  for (const key of ['events', 'forms', 'tickets', 'assets', 'articles', 'items', 'data']) {
    const value = data[key]
    if (Array.isArray(value)) return value.filter(isRecord)
  }

  return []
}

function isRecord(value: unknown): value is AnyRecord {
  return !!value && typeof value === 'object' && !Array.isArray(value)
}

async function firstRecord(api: ApiClient, path: string): Promise<AnyRecord | null> {
  const res = await api.get<unknown>(path)
  expect(res.status, `${path} returned ${res.status}`).toBeLessThan(500)
  if (!res.body.ok) return null
  return recordsFrom(res.body.data)[0] ?? null
}

async function findOrCreateEvent(api: ApiClient): Promise<{ id: string; created: boolean }> {
  const event = await firstRecord(api, '/api/events?limit=5')
  const existingId = stringField(event, 'id')
  if (existingId) return { id: existingId, created: false }

  const start = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)
  start.setMinutes(0, 0, 0)
  const end = new Date(start.getTime() + 60 * 60 * 1000)
  const created = await api.post<AnyRecord>('/api/events', {
    title: `Dynamic page audit ${Date.now()}`,
    description: 'Generated by the dynamic page E2E coverage check.',
    room: `E2E dynamic room ${Date.now()}`,
    startsAt: start.toISOString(),
    endsAt: end.toISOString(),
    requiresAV: false,
    attendeeIds: [],
  })

  expect(created.status, `event create returned ${created.status}`).toBe(201)
  expect(created.body.ok, JSON.stringify(created.body)).toBe(true)
  const eventId = created.body.ok ? stringField(created.body.data, 'id') : null
  expect(eventId, 'created event did not include an id').toBeTruthy()
  return { id: eventId!, created: true }
}

function stringField(record: AnyRecord | null, field: string): string | null {
  const value = record?.[field]
  return typeof value === 'string' && value.length > 0 ? value : null
}

async function expectRouteLoads(page: Page, route: string) {
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))

  const response = await page.goto(route, { waitUntil: 'domcontentloaded' }).catch(() => null)
  expect(response, `${route} did not return a browser response`).not.toBeNull()
  expect(response!.status(), `${route} returned ${response!.status()}`).toBeLessThan(500)

  await page.waitForLoadState('networkidle', { timeout: 15_000 }).catch(() => {})
  await expect(page.locator('body')).toBeVisible()
  await expect(page.locator('body')).not.toContainText(/application error|something went wrong/i)
  expect(pageErrors, pageErrors.join('\n')).toHaveLength(0)
}

test.describe('Dynamic real-record pages', () => {
  test.afterAll(async () => {
    await rawPrisma.$disconnect()
  })

  test('event detail and day-of pages load with a real event', async ({ adminApi, adminPage }) => {
    const event = await findOrCreateEvent(adminApi)

    await expectRouteLoads(adminPage, `/events/${event.id}`)
    await expectRouteLoads(adminPage, `/events/${event.id}/dayof`)

    if (event.created) {
      await adminApi.delete(`/api/events/${event.id}`).catch(() => null)
    }
  })

  test('form builder loads with a real form', async ({ adminApi, adminPage }) => {
    const form = await firstRecord(adminApi, '/api/forms/hub')
    const formId = stringField(form, 'id')
    if (!formId) test.skip(true, 'No form record available for dynamic page check')

    await expectRouteLoads(adminPage, `/forms/${formId}/builder`)
  })

  test('maintenance detail pages load with real records', async ({ adminApi, adminPage }) => {
    const asset = await firstRecord(adminApi, '/api/maintenance/assets?limit=5')
    const assetId = stringField(asset, 'id')
    if (assetId) await expectRouteLoads(adminPage, `/maintenance/assets/${assetId}`)

    const article = await firstRecord(adminApi, '/api/maintenance/knowledge-base?limit=5')
    const articleId = stringField(article, 'id')
    if (articleId) await expectRouteLoads(adminPage, `/maintenance/knowledge-base/${articleId}`)

    const ticket = await firstRecord(adminApi, '/api/maintenance/tickets')
    const ticketId = stringField(ticket, 'id')
    if (ticketId) await expectRouteLoads(adminPage, `/maintenance/tickets/${ticketId}`)

    if (!assetId && !articleId && !ticketId) {
      test.skip(true, 'No maintenance records available for dynamic page check')
    }
  })

  test('tenant dynamic pages load for the test organization slug', async ({ adminPage }) => {
    await expectRouteLoads(adminPage, `/${env.orgA.slug}/events`)
    await expectRouteLoads(adminPage, `/${env.orgA.slug}/facilities`)
    await expectRouteLoads(adminPage, `/${env.orgA.slug}/settings`)
  })

  test('public registration and QR pages load with real records when available', async ({ page, adminPage }) => {
    const registrationForm = await rawPrisma.registrationForm.findFirst({
      where: { organizationId: env.orgA.id },
      select: {
        shareSlug: true,
        organization: { select: { slug: true } },
      },
    })

    if (registrationForm) {
      await expectRouteLoads(page, `/events/public/${registrationForm.organization.slug}/${registrationForm.shareSlug}`)
      await expectRouteLoads(page, `/events/public/${registrationForm.organization.slug}/${registrationForm.shareSlug}/register`)
      await expectRouteLoads(page, `/r/${registrationForm.shareSlug}`)
    }

    const publicForm = await rawPrisma.formDefinition.findFirst({
      where: { organizationId: env.orgA.id, isPublic: true, status: 'ACTIVE' },
      select: { id: true },
    })
    if (publicForm) {
      await expectRouteLoads(page, `/f/${publicForm.id}`)
    }

    const qrCode = await rawPrisma.formQrCode.findFirst({
      where: { organizationId: env.orgA.id, active: true },
      select: { token: true },
    })
    if (qrCode) {
      await expectRouteLoads(page, `/f/qr/${qrCode.token}`)
    }

    const eventTicket = await rawPrisma.eventTicket.findFirst({
      where: { organizationId: env.orgA.id },
      select: { ticketCode: true },
    })
    if (eventTicket) {
      await expectRouteLoads(page, `/tickets/${eventTicket.ticketCode}`)
    }

    const checkInForm = await rawPrisma.formDefinition.findFirst({
      where: { organizationId: env.orgA.id },
      select: { id: true },
    })
    if (checkInForm) {
      await expectRouteLoads(adminPage, `/check-in/${checkInForm.id}`)
    }

    if (!registrationForm && !publicForm && !qrCode && !eventTicket && !checkInForm) {
      test.skip(true, 'No public registration, public form, QR, ticket, or check-in records available')
    }
  })

  test('public athletics pages load with real organization and player data when available', async ({ page }) => {
    await expectRouteLoads(page, `/athletics/public/${env.orgA.slug}`)

    const athlete = await rawPrisma.athlete.findFirst({
      where: { organizationId: env.orgA.id, isActive: true },
      select: { id: true },
    })
    if (athlete) {
      await expectRouteLoads(page, `/athletics/public/player/${athlete.id}`)
    }
  })

  test('event participant self-service page loads with a real registration when available', async ({ page }) => {
    const registration = await rawPrisma.eventRegistration.findFirst({
      where: { organizationId: env.orgA.id, deletedAt: null },
      select: { id: true },
    })
    if (!registration) test.skip(true, 'No event registration available for participant self-service page')

    await expectRouteLoads(page, `/events/check-in/${registration.id}`)
  })

  test('platform-admin dynamic pages load with a real platform token when available', async ({ page }) => {
    const platformAdmin = await rawPrisma.platformAdmin.findFirst({
      select: { id: true, email: true, name: true, role: true },
    })
    if (!platformAdmin) test.skip(true, 'No platform admin available for platform detail pages')

    const token = await signPlatformAuthToken({
      adminId: platformAdmin.id,
      email: platformAdmin.email,
    })
    await page.addInitScript(
      ({ token, admin }) => {
        window.localStorage.setItem('platform-token', token)
        window.localStorage.setItem('platform-admin', JSON.stringify(admin))
      },
      {
        token,
        admin: {
          id: platformAdmin.id,
          email: platformAdmin.email,
          name: platformAdmin.name,
          role: platformAdmin.role,
        },
      },
    )

    await expectRouteLoads(page, `/admin/schools/${env.orgA.id}`)

    const supportTicket = await rawPrisma.platformSupportTicket.findFirst({
      select: { id: true },
    })
    if (supportTicket) {
      await expectRouteLoads(page, `/admin/support/${supportTicket.id}`)
    }
  })
})
